name: Build and deploy .NET application to container app robocontroleapi-app-202403260946
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: robocontroleapi
  CONTAINER_APP_NAME: robocontroleapi-app-202403260946
  CONTAINER_APP_RESOURCE_GROUP_NAME: estudos
  CONTAINER_REGISTRY_LOGIN_SERVER: robocontroleapi20240326095003.azurecr.io
  DOCKER_FILE_PATH: Dockerfile
  PROJECT_NAME_FOR_DOCKER: robocontrole.api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.RoboControleApi20240326095003_USERNAME_7103 }}
        password: ${{ secrets.RoboControleApi20240326095003_PASSWORD_7103 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.robocontroleapi_app_202403260946_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.RoboControleApi20240326095003_USERNAME_7103 }} --password ${{ secrets.RoboControleApi20240326095003_PASSWORD_7103 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
